name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install NPM packages
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Export project
        run: yarn run export

      - name: Create NoJekyll File
        run: touch ./out/.nojekyll

      - name: Run unit tests
        run: yarn run test

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.ts

      - name: Upload production-ready build files
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
